version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432"
    environment:
      - AIR_ALERT_PGPASS
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${PWD}/scripts:/docker-entrypoint-initdb.d:ro
      - ${PWD}/data/postgres:/var/lib/postgresql/data:rw
  redis:
    image: redis:6-alpine
    ports:
      - "6379"
    volumes:
      - ${PWD}/data/redis:/data:rw
  airalert:
    image: mrflynn/airalert:latest
    ports:
      - "3000:3000"
    environment:
      - AIR_ALERT_DATABASE_POSTGRES_PASSWORD=${AIR_ALERT_PGPASS}
    volumes:
      - ${PWD}/config.toml:/config.toml:ro
    depends_on:
      - postgres
      - redis