name: Tests

on:
  push:
    paths:
      - '**/*.go'
      - go.(mod|sum)?
      - .github/workflows/test.yml

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.7
      - name: Run unit tests
        run: |
          go test -tags=unit -v -race $(go list ./... | grep -v models)
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.7
      - name: Set env variables
        run: |
          export PGPASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1)
          export DBSPEC=$(pwd)/config/sql/users.sql

          echo "::set-env name=PGUSER::airalert"
          echo "::set-env name=PGDBNAME::airalert"
          echo "::set-env name=PGPASS::$PGPASS"
          echo "::set-env name=DBSPEC::$DBSPEC"

          echo "::add-mask::$PGPASS"
      - name: Setup PostgreSQL Database
        run: |
          docker run \
            -e POSTGRES_USER=$PGUSER -e POSTGRES_PASSWORD=$PGPASS -e POSTGRES_DB=$PGDBNAME \
            --name test-postgres \
            -p 5432:5432 \
            --rm -d postgres:12
      - name: Run integration tests
        run: |
          go test -tags=integration -v -race $(go list ./... | grep -v models)
      - name: Cleanup
        if: ${{ always() }}
        run: |
          docker stop test-postgres
          
